"""adds register date

Revision ID: 32d24e717b78
Revises: 84b5f6fd3276
Create Date: 2021-07-29 18:19:43.143543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d24e717b78'
down_revision = '84b5f6fd3276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('register_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'register_date')
    # ### end Alembic commands ###
