"""Add likes

Revision ID: a90f5eee009a
Revises: ac0cdf0ac720
Create Date: 2021-07-30 18:39:41.474294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a90f5eee009a'
down_revision = 'ac0cdf0ac720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('user_1', sa.Integer(), nullable=False),
    sa.Column('user_2', sa.Integer(), nullable=False),
    sa.Column('user_1_liked', sa.Boolean(), nullable=False),
    sa.Column('user_2_liked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_1'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_2'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_1', 'user_2')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    # ### end Alembic commands ###
